# -*- coding: utf-8 -*-
"""loan_predication_deployment.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QhOwTu8V1boy0aj_5r8HP1TKjSHELW3
"""
import streamlit as st
import pandas as pd
import joblib

# Load Model
model = joblib.load("loan_prediction_model.pkl")

st.title("🏦 Loan Prediction App")

st.write("Enter Applicant Details:")

# Inputs
Gender = st.selectbox("Gender", ["Male", "Female"])
Married = st.selectbox("Married", ["Yes", "No"])
Education = st.selectbox("Education", ["Graduate", "Not Graduate"])
Self_Employed = st.selectbox("Self Employed", ["Yes", "No"])
ApplicantIncome = st.number_input("Applicant Income", min_value=0)
CoapplicantIncome = st.number_input("Coapplicant Income", min_value=0)
LoanAmount = st.number_input("Loan Amount", min_value=0)
Loan_Amount_Term = st.number_input("Loan Amount Term", min_value=0)
Credit_History = st.selectbox("Credit History", [1, 0])
Property_Area = st.selectbox("Property Area", ["Urban", "Semiurban", "Rural"])

# Manual Encoding
Gender = 1 if Gender == "Male" else 0
Married = 1 if Married == "Yes" else 0
Education = 1 if Education == "Graduate" else 0
Self_Employed = 1 if Self_Employed == "Yes" else 0

if Property_Area == "Urban":
    Property_Area = 2
elif Property_Area == "Semiurban":
    Property_Area = 1
else:
    Property_Area = 0

# Create DataFrame (ORDER MUST MATCH TRAINING DATA)
df = pd.DataFrame({
    "Gender": [Gender],
    "Married": [Married],
    "Education": [Education],
    "Self_Employed": [Self_Employed],
    "ApplicantIncome": [ApplicantIncome],
    "CoapplicantIncome": [CoapplicantIncome],
    "LoanAmount": [LoanAmount],
    "Loan_Amount_Term": [Loan_Amount_Term],
    "Credit_History": [Credit_History],
    "Property_Area": [Property_Area]
})

# Prediction
if st.button("Predict Loan Approval"):
    prediction = model.predict(df)

    if prediction[0] == 1:
        st.success("Loan Approved")
    else:
        st.error(" Loan Not Approved")
