# -*- coding: utf-8 -*-
"""loan predication .arpita bhoir .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wVYLc8nRag9XPO6tax7T_iGWTKiF2qiB
"""

from google.colab import drive
drive.mount('/content/drive')

filepath = "/content/drive/MyDrive/arpita.machine learning with python/Loan prediction (1).csv"

import pandas as pd

data = pd.read_csv(filepath)

data.head(5)

data.shape

data.columns

data.info()

data.describe()

data.isna().sum()

data = data.dropna()

data["ApplicantIncome"].unique()

data["Gender"].unique()

data["Gender"].value_counts()

data["ApplicantIncome"].value_counts()

data.duplicated().sum()

data= data.drop_duplicates()

data["Gender"] = data["Gender"].str.lower()

data["Gender"]= data["Gender"].str.strip()

"""**Data** **Visualization**"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(data["Gender"],color = "yellow")
plt.title("Gender Distribution")
plt.show()

sns.histplot(data["Dependents"],color = "red")
plt.title("Dependents Distribution")
plt.show()

sns.histplot(data["LoanAmount"],color = "green",bins = 20, kde= True)
plt.title("LoanAmount")
plt.show()

sns.countplot(data["Gender"],color="green")
plt.title("countplot of Gender")
plt.show()

sns.countplot(data["Dependents"],color="red")
plt.title("Dependents")
plt.show()

sns.boxplot(data["Dependents"],color="skyblue")
plt.show()

sns.boxplot(data["LoanAmount"],color="skyblue")
plt.show()

# scatterplot
sns.scatterplot(data=data, x="ApplicantIncome", y="Gender")
plt.title("scatterplot between ApplicantIncome and Gender")
plt.show()

sns.scatterplot(data=data, x="Credit_History", y="LoanAmount")
plt.title("scatterplot between Credit_History and LoanAmount")
plt.show()

# label encoding
from sklearn.preprocessing import LabelEncoder

#le = LabelEncoder()
#data["Education Level"] = le.fit_transform(data["Education Level"])

label_encoder = {}
for col in data.select_dtypes(include="object"):
  le = LabelEncoder()
  data[col] = le.fit_transform(data[col])
  label_encoder[col] = le

data.info()

sns.heatmap(data.corr(),annot = True ,
            cmap="Blues")
plt.show()

data.skew(numeric_only=True)

# splitting data into features and target variable
x = data.drop("Dependents",axis=1) # features
y = data["Dependents"] # target variable

# splitting in train and test data
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)# splitting in train and test data
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

# linear regression

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

y_pred_lr = lr.predict(x_test)

# r2 score
from sklearn.metrics import r2_score

r2_lr = r2_score(y_test,y_pred_lr)
print(r2_lr)

# decision tree regressor
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(x_train,y_train)

y_pred_dtr = dtr.predict(x_test)

r2_dtr = r2_score(y_test,y_pred_dtr)

print(r2_dtr)

# randomforest regressor
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(x_train,y_train)

y_pred_rfr = rfr.predict(x_test)

r2_rfr = r2_score(y_test,y_pred_rfr)
print(r2_rfr)

# downloading the model
import joblib
joblib.dump(rfr,"loan_prediction_model.pkl")

# download in system
from google.colab import files
files.download("loan_prediction_model.pkl")

# label encoder
joblib.dump(label_encoder,"label_encoder.pkl")
files.download("label_encoder.pkl")